name: fitness_dashboard_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  provider: ^6.0.5
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  fl_chart: ^0.67.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  url_launcher: ^6.3.1
  http: ^1.3.0
  socket_io_client: ^3.1.1
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  emoji_picker_flutter: ^4.3.0
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  postgrest: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
